### ISSUE TITLE
drill down views when clicking on ERDDAP image maps

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/mbon-dashboard-server#16]
User requests regional drill down from map click. Specific regions of interest are FL east coast and FK reef tract. 

Although doing it from a map click is too hard, links to relevant drilldowns could be placed. Let's try it out.

Drilldowns should have zoomed in views of the maps and... I guess that is it?

**Comment by 7yl4r** [comment]
since a zoomed in map of the two regions is all that is really being asked for it may be easier to just manually include two links to zoomed in ERDDAP images.

**Comment by 7yl4r** [comment]
from Dan's email:

> TODO: Drill-down board? All we really need is a way to zoom in. Maybe even just new dashboards for the "reef tract" and "south east florida". Whatever is doable.

**Comment by 7yl4r** [comment]
@dotis : I am thinking about this more and I agree the best solution is to have two new dashboards for the "reef tract" and "SE FL". 

The easiest way to do that is to duplicate & modify the current dashboard. Because of this I want to finalize the "main" dashboard before creating these subregion dashboards. I have made some changes to the dashboards. Please take a look, make any final changes, and let me know when you think they are ready. 

The timeseries data still isn't there (it has turned into a major pain) but I remain confident the data will be in there soon. Worst case we can curl the files manually.

**Comment by dotis** [comment]
Ok. I'll take a look in the morning. Were you able to add the gifs and river panel?
________________________________

**Comment by 7yl4r** [comment]
Yes, gifs and river panel are added. I think the river data will work once the backend is working but hard to say without testing it.

**Comment by dotis** [comment]
I made some minor edits and copied in the json. I think things look good for now. I need to clean up the animations. I think we may just want to use the map one and not the graph.

**Comment by 7yl4r** [comment]
I have added the drilldowns but I don't know where to link to them or whether they are really useful:

* http://35.208.211.184:3000/d/RRa51qeGz/biscayne-bay-and-southeast-florida-drilldown
* http://35.208.211.184:3000/d/k7kraqeMk/keys-reef-tract-drilldown

@dotis : I think the best place to put links for these is in the Introduction or More Information. The other option is to put the links in the tooltip that appears when you hover over a little `i` in the top left of the panel. It looks like this:

![image](https://user-images.githubusercontent.com/1051390/121597700-06108c00-ca0f-11eb-92cc-d38555ce85c0.png)

What do you think? Tooltip, intro, more info, leave them out for now or something else?

**Comment by dotis** [comment]
I think maybe in the intro. I’m not sure how to increase font size, but maybe a short bit of text in bold in a slightly larger font.

________________________________

**Comment by 7yl4r** [comment]
Added the links and made some formatting changes to the intro. Anything else we should do for the drilldowns?

**Comment by dotis** [comment]
Are they just copies, each with their own branch?

________________________________

**Comment by dotis** [comment]
Is it live? Can I check the regions?

________________________________

**Comment by 7yl4r** [comment]
Yes, it's live. The subregion boards are copies but with different
coordinates for the grafana-ERDDAP panels. I put links to them in the
intro. They don't have their own git branches, they are additional
json files.
