### ISSUE TITLE
map of coral disease spread over time

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/mbon-dashboard-server#17]
It would be great to have a more detailed graph like the one here https://floridakeys.noaa.gov/coral-disease/disease.html which shows the disease spreading animated on a map.

I tried doing this using a few existing panels but wasn't able to make it work easily. The data is noisy and doesn't align well organizationally with what the existing geospatial panels need to work. Cleaning and transformation would be needed in addition to maybe standing up some web services.

We could just include that map gif or something similar though. 😅

**Comment by 7yl4r** [comment]
updated gif from @dotis:

![FK_SCTLD_advance_images](https://user-images.githubusercontent.com/1051390/120506226-b9381000-c393-11eb-9a38-80eb940ec460.gif)

and updated panels:

![image](https://user-images.githubusercontent.com/1051390/120506571-0b793100-c394-11eb-9a0f-7ba122da2cf2.png)

**Comment by 7yl4r** [comment]
While uploading the `.gif` files I download earlier I also found this plot:

![image](https://user-images.githubusercontent.com/1051390/120582633-c89e7400-c3fa-11eb-97a1-90e450919c2d.png)

I uploaded this to `/static_files/` too but have no plans to add it to the dashboard. Should we add it or delete it from `/static_files/`?

**Comment by dotis** [comment]
Hmm. I don't think it will go on the dashboard. We can delete it.
________________________________
