### ISSUE TITLE
new river panel

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/mbon-dashboard-server#25]
from Dan's email:

> TODO: New river panel (moving to three total - west, east, st. lucie)

**Comment by 7yl4r** [comment]
just added to the ts_ingest dag

**Comment by 7yl4r** [comment]
oops. also need to add the panel

**Comment by dotis** [comment]
I have made a bunch of updates. I added the new maps and disease panel. I have saved the json file, but have not copied it into github yet. Should I go ahead and do that?

**Comment by 7yl4r** [comment]
yes, please feel free to go ahead. git never deletes anything so I can always roll back if needed.

**Comment by dotis** [comment]
Ok. I copied it in.

**Comment by 7yl4r** [comment]
Just pulled it to the server. Please close this is if it looks good.

**Comment by dotis** [comment]
It looks good. I can close, but the issue thread is actually for the new river panel, which is still active.
