### ISSUE TITLE
Some users can't access dashboard link

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#38]
This is an issue on the user's end and is most likely a browser issue, but is possibly due to an http link as opposed to https. Can security settings screen http links?

**Comment by dotis** [comment]
User used another browser.

**Comment by 7yl4r** [comment]
If you know any of the following it might help us if this pops up again.

* What browser was having the issue?
* What browser worked?
* what Operating system (windows?)
* what physical location (US?)
* what type of network (home or work or government?)
