### ISSUE TITLE
Question on ts_ingest.py

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#47]
In the ts_ingest.py files, I see the following section. I'm curious if/how (and why) VSNPP is being used here. Is this where the selection of which time series extractions to display are set? The following is from the FGB branch, but that board is currently displaying MODIS extractions, so I'm not sure why VSNPP is set in the table below.

 In any case, we should match the time series to the imagery.

Perhaps like this:
FGBNMS (use MODIS)
FKNMS (use MODIS)
FWC (use VSNPP)

 
```python
   SAT_FILE_DETAIL_LIST = [
        # sat    | product
        ["VSNPP", "chlor_a"],
        ["VSNPP", "Rrs_671"],
        ["VSNPP", "Kd_490"],
        ["VSNPP", "sstn"],
        ["MODA",  "ABI"],
    ]
    # example path: `GOMdbv2_ABI_TS_MODA_daily_Alderice.csv`
    SAT_FPATH = (
        "{REGION}dbv2_{product}_TS_{sat}_daily_{roi}.csv"
    )
    for roi in SAT_ROI_LIST:
        for sat, product in SAT_FILE_DETAIL_LIST:
            BashOperator(
                task_id=f"ingest_sat_roi_{REGION}_{sat}_{product}_{roi}",
                bash_command=(
```

**Comment by 7yl4r** [comment]
You can check the list and status of the airflow jobs created by this at the URL:

http://fknms-dashboard.marine.usf.edu:8888/
