### ISSUE TITLE
FGBNMS DAG runs failing

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#51]
When running FK and FGB DAGs today, the FK worked fine, but the FGB failed for all runs. All FGB DAG runs failed on 7/23 and 7/24 as well. We will have a demo of this board on Thursday 7/27.

**Comment by 7yl4r** [comment]
The mbon-uploader docker container had died. nothing in the logs. restarted with `docker compose up -d` and all is well again.
