### ISSUE TITLE
TODO items from 2023-12-15 meeting 

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/mbon-dashboard-server#60]
Attending: Jenn Dorton, Chris Simonello, Dan Otis, Tylar Murray

* [ ] (@dotis) misspelled in image at top Sapello -> Sapelo 
* [x] Jenn: not clear how dropdowns are connected to the panels
    * Tylar suggests breaking this into multiple dashboards
    * We need to better identify the "use cases" meeting in Jan will help with this.

**Comment by dotis** [comment]
"Sapelo" is fixed in the map image and text below.
