### ISSUE TITLE
ERDDAP is not updating

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#65]
Updated ERDDAP files are in the dune directory, but are not appearing on the ERDDAP server. No datasets are failing on the status page and existing files are there as normal.

**Comment by 7yl4r** [comment]
I think this is fixed due to changes in erddap-config. The [ERDDAP status page](http://dune.marine.usf.edu:8080/erddap/status.html) no longer shows datasets.xml error and I checked one of the datasets appears up to date (latest is 2024-02-25). One dataset is still failing however.
