### ISSUE TITLE
Need to get FWC dash running

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#66]
I was asked by FWC about this. The larger extent is what they want to see. This should not be too hard. Things seem fairly organized in the 'client-fwc' branch.

**Comment by 7yl4r** [comment]
I tried starting the existing FWC VM in google cloud but ran into issues. It may be that the allocated hard drive is too small and ran out of space. 

I created a new, beefier VM based on what we are using for FKNMS & SEUS.
I walked through the client setup script and updated it for the new OS. 
I rebased the client-fwc branch so updates on master get copied over.
I started things up and the stack looks ok.
The ERDDAP urls are out-of-date so the sat imagery is not there.

**Comment by dotis** [comment]
Ok. I can try to update things as best I can. Thanks.

**Comment by dotis** [comment]
ERDDAP urls are updated. Still a few small items remain, but we can share the link ([issue](https://github.com/marinebon/mbon-dashboard-server/issues/69)).

**Comment by dotis** [comment]
The updates to the json files do not seem to be getting on the site. Is there a manual push that needs to happen? I recall this happened in the past.
