### ISSUE TITLE
ts_ingest DAG is not running on SEUS dash

### ISSUE THREAD

**Issue by dotis** [marinebon/mbon-dashboard-server#67]
I tried to add some code to the [DAG](https://github.com/marinebon/mbon-dashboard-server/blob/client-seus/airflow/dags/ts_ingest.py) to ingest NERR data (.csv files that I generated). There were some errors in the DAG, which I fixed, but the DAG has never restarted even after I commented out the new code (at the bottom).

**Comment by 7yl4r** [comment]
resolved by manually marking the DAG failed in the airflow web ui
